<?php

namespace Database\Seeders;

use App\Models\Availability;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AvailabilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Availability::insert([
            //Erdi
            ['assistant_id' => 1, 'period_id' => 1, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 2, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 3, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 4, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 5, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 6, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 7, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 8, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 9, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 10, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 11, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 12, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 13, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 14, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 15, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 16, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 17, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 18, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 19, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 20, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 21, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 22, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 23, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 24, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 25, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 26, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 27, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 28, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 29, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 30, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 31, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 32, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 33, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 34, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 35, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 36, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 37, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 38, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 39, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 40, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 41, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 42, 'is_available' => false], 
            ['assistant_id' => 1, 'period_id' => 43, 'is_available' => true], 
            ['assistant_id' => 1, 'period_id' => 44, 'is_available' => true],
            ['assistant_id' => 1, 'period_id' => 45, 'is_available' => true],
            ['assistant_id' => 1, 'period_id' => 46, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 47, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 48, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 49, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 50, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 51, 'is_available' => false],
            ['assistant_id' => 1, 'period_id' => 52, 'is_available' => true],
            ['assistant_id' => 1, 'period_id' => 53, 'is_available' => true],
            ['assistant_id' => 1, 'period_id' => 54, 'is_available' => true],

            //ZD
            ['assistant_id' => 2, 'period_id' => 1, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 2, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 3, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 4, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 5, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 6, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 7, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 8, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 9, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 10, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 11, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 12, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 13, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 14, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 15, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 16, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 17, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 18, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 19, 'is_available' => true], 
            ['assistant_id' => 2, 'period_id' => 20, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 21, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 22, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 23, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 24, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 25, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 26, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 27, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 28, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 29, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 30, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 31, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 32, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 33, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 34, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 35, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 36, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 37, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 38, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 39, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 40, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 41, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 42, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 43, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 44, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 45, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 46, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 47, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 48, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 49, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 50, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 51, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 52, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 53, 'is_available' => true],
            ['assistant_id' => 2, 'period_id' => 54, 'is_available' => true],
        ]);
    }
}
